### ISSUE TITLE
Consider combining confidentiality and integrity bounds for an AE bound

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-aead-limits#12]
[1] notes that bounds on confidentiality (IND-CPA) and integrity (IND-CXTX) success probability can be added to produce bounds on the AE security. Should we note this, and present that bound?

[1] https://www.isg.rhul.ac.uk/~kp/TLS-AEbounds.pdf

**Comment by fxguenther** [comment]
I'd say it makes sense to note that the bounds can be combined. Not sure giving the bounds for each scheme adds much – also, were would one _not_ consider CA and IA separately?

That made me think: Should we have (semi-)formal definitions for the CA/IA bounds and AE security?

**Comment by chris-wood** [comment]
> I'd say it makes sense to note that the bounds can be combined. Not sure giving the bounds for each scheme adds much – also, were would one not consider CA and IA separately?

I don't have a use case in mind right now. I imagine applications would track both limits and then re-key whenever one's hit (or near being hit). Should we add recommendations for implementations here?

> That made me think: Should we have (semi-)formal definitions for the CA/IA bounds and AE security?

That'd be good. Do you want to take a crack at this?
