### ISSUE TITLE
John Mattsson's analysis

### ISSUE THREAD

**Issue by thomas-fossati** [cfrg/draft-irtf-cfrg-aead-limits#37]
In his [presentation](https://datatracker.ietf.org/meeting/110/materials/slides-110-saag-analysis-of-usage-limits-of-aead-algorithms-00.pdf) to SAAG at IETF 110 @emanjon made a few points regarding ChaCha/Poly and CCM_8 -- see slide 11 for the summary.  Have those being considered?

**Comment by thomas-fossati** [comment]
When one plugs the numbers into the equations, CCM8’s integrity limits effectively come out as tragically low.  The immediate consideration that comes to mind is if CCM8 is so fragile, its integrity should have been successfully broken many times over?   (Considering it is pretty widely deployed in the embedded world, it’d seem that the surface should be large enough to make such attacks very practical.)  And yet, I couldn't find any published work that documents such an attack.  (To paraphrase [Fermi](https://en.wikipedia.org/wiki/Fermi_paradox): "where is everybody?” :-))  So, the subsequent thought is: is the model on which the equations are built correct?  Why are the number in such sharp contrast with the (naive) intuition that CBC-MAC should behave like a perfect MAC?

**Comment by martinthomson** [comment]
So CCM8 does appear tragically weak.  It does that on the basis of an analysis that shows that it is nearly perfect.  That said, it's a fairly simplistic analysis; it's possible that tighter bounds exist that produce large values for *p* and *q*.

Don't assume that the absence of attacks provides that something can't be attacked.  Consider incentives.  For attackers, most likely it just suggests that there are more fruitful avenues open to them.  For academics, demonstrating or theorizing about a brute force attack is hardly going to get a whole of attention or recognition.

**Comment by thomas-fossati** [comment]
> So CCM8 does appear tragically weak. It does that on the basis of an analysis that shows that it is nearly perfect. That said, it's a fairly simplistic analysis; it's possible that tighter bounds exist that produce large values for _p_ and _q_.

The thing is If we were really confident about the CCM8 IL figures, we should go and tell the industry they _must not_ use this anymore, and they are better off making sure that their boxes are either updated or nuked as soon as possible.  (And this would, at least, include the boxes that talk [DTLS-secured CoAP](https://datatracker.ietf.org/doc/html/rfc7252#section-9.1) and [OSCORE](https://datatracker.ietf.org/doc/html/rfc8613#section-3.2).)

OTOH, if we are not sure that the numbers are right we should seek a more precise characterisation for the CCM8 limits.

**Comment by martinthomson** [comment]
Yes, maybe we should be more confident in the analysis before upending an industry.  But it's hard work and wishful thinking won't make that work happen.  I would prefer to leave things as they stand, with the implication being that there is uncertainty about what means for people using CCM8.  We could point out what this might mean for users of CCM8, but I don't think that a CFRG document is the best place to make that point though.

**Comment by thomas-fossati** [comment]
> Yes, maybe we should be more confident in the analysis before upending an industry. But it's hard work and wishful thinking won't make that work happen. I would prefer to leave things as they stand, with the implication being that there is uncertainty about what means for people using CCM8. We could point out what this might mean for users of CCM8, but I don't think that a CFRG document is the best place to make that point though.

I agree. uta-tls13-iot-profile is probably the right place to make that fact clear (also pointing to Appendix B.2 of [NIST's recommendation for CCM](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38c.pdf)) and start some sort of soft deprecation.
