### ISSUE TITLE
Document different v and q use cases

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-aead-limits#4]
`v` and `q` may vary depending on use case, and the bounds may simplify significantly depending on those bounds. For example, in QUIC, we assume `v >> q`, which lets us treat `v` as negligible compared to `v^2`.

**Comment by chris-wood** [comment]
Hmm, I think we may disagree on that last point. The limits we're talking about here apply more directly to packet counts (assuming we're using the same definition for that). 

In any case, I'll see if I can throw up a PR describing these different use cases shortly!

**Comment by martinthomson** [comment]
I understand that, but the problem is that the cases that matter involve asking your counterpart to make a change, which takes time, not packets.

**Comment by chris-wood** [comment]
I think has been overcome by events. Closing for now.
