### ISSUE TITLE
GCM SU IA limit

### ISSUE THREAD

**Issue by martinthomson** [cfrg/draft-irtf-cfrg-aead-limits#55]
From Scott Fluhrer:

> In section 5.1.2, you give IA = 2 * (v * (L+1)) / 2^128; however the cited paper (GCMProofs, Corollary 4) gives a second term for this; it is not obvious to me that the second term is always negligible.

I couldn't work out why we eliminated the other term either.  It seems to me like that term is indeed relevant, or even dominant.

![image](https://user-images.githubusercontent.com/67641/219195240-ae995f37-4dda-4c2e-b648-22ad96424f35.png)

Is this a degenerate form of the MU results instead?  We have `AEA <= (q+v)*l*B / 2^127` there, which doesn't map to the IA result as far as I can see.

**Comment by fxguenther** [comment]
The bound is actually fine, since we're basing off Equation (22) in the paper which gives a better bound. I've added some explanation, cf. #57.

**Comment by chris-wood** [comment]
Closing as resolved by #57.
